---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

```{r}
rm(list = ls())
library(reticulate)
library(RVerbalExpressions)
library(stringr)
```

```{python}
import requests
import random

query = "keep dog off couch"

r = requests.get("https://api.qwant.com/api/search/images",
                 params={
                   'count': 200,
                   'q': query,
                   't': 'images',
                   'safesearch': 1,
                   'locale': 'en_US',
                   'uiv': 4
                 },
                 headers={
                   'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36'
                 }
)

response = r.json().get('data').get('result').get('items')
urls = [r.get('media') for r in response]
```

```{r}
urls <- start_of_line() %>% 
  find("http") %>% 
  maybe("s") %>% 
  then("://") %>%
  str_remove(py$urls, .)


```

```{r}
url_names <- 
  start_of_line() %>% 
  anything() %>% 
  any("/") %>% 
  str_remove(urls, .)
```

Create image folder
```{r}
image_folder = 'images'
if(!dir.exists(image_folder)) {
  dir.create(image_folder)
  dir.create(paste0(image_folder, "/dogs_on_couch"))
  dir.create(paste0(image_folder, "/dogs_off_couch"))
}
```

```{r}
download.file(urls, paste0(image_folder, "/dogs_off_couch/", url_names))
```

```{r}

```